version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-chat
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local
